language: node_js
node_js:
  - "6.9.4"
cache:
  directories:
    - node_modules
install:
  - npm install
env:
  - TEST_TYPE=lint
  - TEST_TYPE=unit-test
  - TEST_TYPE=integration-test
script:
  - npm run $TEST_TYPE
